package main

import "math"

// StormLevel describes what the audio engine should play.
// Generated by MapWPMToStorm() 20 times per second.
type StormLevel struct {
	Intensity   float64    // 0.0 (silent) to 1.0 (full storm)
	RainVolume  [3]float64 // volume for [light, medium, heavy] rain layers
	CanThunder  bool       // should thunder be possible right now?
	ThunderProb float64    // probability of thunder per tick (0.0 - 0.25)
}

// MapWPMToStorm converts typing speed and idle time to a storm description.
//
// The mapping:
//
//	0 WPM (idle 4s+)   → silence
//	1-20 WPM            → light rain
//	20-40 WPM           → light + medium rain crossfade
//	40-60 WPM           → medium rain dominant
//	60-90 WPM           → heavy rain, occasional thunder
//	90-120+ WPM         → full storm, frequent thunder
func MapWPMToStorm(wpm float64, idleSec float64) StormLevel {
	var level StormLevel

	// ── IDLE FADE ──
	// When you stop typing, the storm fades over ~3 seconds.
	// 0-1s idle: full intensity (keep the vibe going briefly)
	// 1-4s idle: fading
	// 4s+ idle:  silent
	idleFade := 1.0
	if idleSec > 1.0 {
		idleFade = math.Max(0, 1.0-(idleSec-1.0)/3.0)
	}

	// ── NORMALIZE WPM TO 0-1 ──
	// 0 WPM = 0.0, 120+ WPM = 1.0
	raw := math.Min(wpm/120.0, 1.0)
	level.Intensity = raw * idleFade

	// ── MAP INTENSITY TO AUDIO LAYERS ──
	switch {
	case level.Intensity < 0.05:
		// Silence — not typing or barely typing
		level.RainVolume = [3]float64{0, 0, 0}

	case level.Intensity < 0.25:
		// Light rain only — gentle patter
		level.RainVolume = [3]float64{
			level.Intensity * 4, // light rain: 0 → 1.0
			0,                   // no medium
			0,                   // no heavy
		}

	case level.Intensity < 0.50:
		// Light fading, medium rising — rain picking up
		t := (level.Intensity - 0.25) / 0.25 // t goes 0→1 in this range
		level.RainVolume = [3]float64{
			1.0 - t*0.5, // light fades to 0.5
			t,            // medium rises to 1.0
			0,            // no heavy yet
		}

	case level.Intensity < 0.75:
		// All three layers, thunder starts — proper storm
		t := (level.Intensity - 0.50) / 0.25
		level.RainVolume = [3]float64{
			0.3,          // light stays as ambience
			1.0 - t*0.3,  // medium fades slightly
			t * 0.7,      // heavy rising
		}
		level.CanThunder = true
		level.ThunderProb = t * 0.1 // up to 10% per tick

	default:
		// Full storm — maximum intensity
		t := (level.Intensity - 0.75) / 0.25
		level.RainVolume = [3]float64{
			0.2,          // light barely audible
			0.5,          // medium half volume
			0.8 + t*0.2,  // heavy nearly full
		}
		level.CanThunder = true
		level.ThunderProb = 0.1 + t*0.15 // 10-25% per tick
	}

	return level
}
